name: Unit Tests

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Install Packages
        id: run-install-pkgs
        run: |
          go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
          git clone https://github.com/google/jsonnet /home/runner/jsonnet
          make -C /home/runner/jsonnet CC=clang CXX=clang++
          sudo cp /home/runner/jsonnet/jsonnet /usr/local/bin
          sudo cp /home/runner/jsonnet/jsonnetfmt /usr/local/bin
          wget https://github.com/prometheus/prometheus/releases/download/v2.29.1/prometheus-2.29.1.linux-amd64.tar.gz
          tar xvf prometheus-2.29.1.linux-amd64.tar.gz
          sudo cp prometheus-2.29.1.linux-amd64/promtool /usr/local/bin/
          sudo cp /home/runner/go/bin/jb /usr/local/bin/
          jb install

      - name: Run Test
        id: run-test
        run: |
          set -o pipefail && find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print |
          while read f; do
          jsonnetfmt -n 2 --max-blank-lines 2 --string-style s --comment-style s "$f" | diff -u "$f" -;
          done
          sudo make all
